# Generated by Django 3.2 on 2021-05-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_district_dist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hosp_img',
            field=models.ImageField(default='blank', upload_to='hospital/images'),
        ),
    ]
